// Mocks generated by Mockito 5.3.2 from annotations
// in todo_assignment/test/features/presentation/bloc/todo/todo_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_assignment/core/error/failures.dart' as _i6;
import 'package:todo_assignment/core/usecases/usecase.dart' as _i8;
import 'package:todo_assignment/features/domain/entities/todo/todo_item.dart'
    as _i7;
import 'package:todo_assignment/features/domain/repositories/todo/todo_repository.dart'
    as _i2;
import 'package:todo_assignment/features/domain/use_cases/todo/load_todos.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodoRepository_0 extends _i1.SmartFake
    implements _i2.TodoRepository {
  _FakeTodoRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoadTodos].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadTodos extends _i1.Mock implements _i4.LoadTodos {
  @override
  _i2.TodoRepository get todoRepository => (super.noSuchMethod(
        Invocation.getter(#todoRepository),
        returnValue: _FakeTodoRepository_0(
          this,
          Invocation.getter(#todoRepository),
        ),
        returnValueForMissingStub: _FakeTodoRepository_0(
          this,
          Invocation.getter(#todoRepository),
        ),
      ) as _i2.TodoRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.TodoItem>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.TodoItem>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.TodoItem>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.TodoItem>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.TodoItem>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.TodoItem>>>);
}
